### ISSUE TITLE
Not able to define number of cores to use when calculating LD

### ISSUE THREAD

**Issue by jinhyunju** [sushilashenoy/zoom.plot#4]
Are you trying to break everyone's computer????

**Comment by sushilashenoy** [comment]
Only yours.

If you are calling `ld.matrix` directly use the option `mc.cores=1` to use a single core, or however many you want. (The default is as many as are reported by `detectCores()`)

If you are using the `zoom.plot` function, add `ld.opts=list('mc.cores'=1)`.
